# Generated by Django 2.1.7 on 2019-09-04 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Overtreding',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('date', models.CharField(max_length=500)),
                ('street', models.CharField(max_length=500)),
                ('driving_direction', models.CharField(max_length=500)),
                ('speed_limit', models.IntegerField()),
                ('passersby', models.IntegerField()),
                ('infractions_speed', models.IntegerField()),
                ('infractions_red_light', models.IntegerField()),
            ],
        ),
    ]
